upstream user_service {
    server user-service:50051;
}

upstream auth_service {
    server auth-service:50052;
}

server {
    listen 80;
    server_name localhost;

    #  API: auth-service
    location /api/auth/ {
        proxy_pass http://auth_service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # API: user-service
    location /api/users/ {
        proxy_pass http://user_service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # HTML-страницы 
    location /dashboard {
        root /usr/share/nginx/html;
        try_files /dashboard.html =404;
    }

    location /auth.AlhelisService/ {
        grpc_pass grpc://auth_service;
        grpc_set_header Host $host;
    }

    # gRPC для user
    location /user.AlhelisService/ {
        grpc_pass grpc://user_service;
        grpc_set_header Host $host;
    }

    # Статика (фронтенд)
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}